[project]
name = "sem-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datasets>=4.4.1",
    "h5py>=3.15.1",
    "huggingface-hub>=1.2.3",
    "ipython>=9.8.0",
    "jupyter>=1.1.1",
    "torch>=2.9.1",
]
